// <auto-generated />
using System;
using BookingService.Infrastructure.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookingService.Migrations
{
    [DbContext(typeof(BookingDbContext))]
    partial class BookingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BookingService.Domain.Entities.Booking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid>("CarPackageId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("package_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DriverId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("driver_id");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("end_date");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime>("LastModifiedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("start_date");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("CarPackageId");

                    b.ToTable("Booking", (string)null);
                });

            modelBuilder.Entity("BookingService.Domain.Entities.CarPackage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid>("CarId")
                        .HasMaxLength(100)
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("car_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime>("LastModifiedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("PackageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("price");

                    b.HasKey("Id");

                    b.HasIndex("PackageId");

                    b.ToTable("PackageType", (string)null);
                });

            modelBuilder.Entity("BookingService.Domain.Entities.DrivingSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("ActualEnd")
                        .HasColumnType("datetime2")
                        .HasColumnName("actual_end_time");

                    b.Property<DateTime>("ActualStart")
                        .HasColumnType("datetime2")
                        .HasColumnName("actual_start_time");

                    b.Property<decimal>("AverageSpeed")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("speed");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("booking_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time")
                        .HasColumnName("end_time");

                    b.Property<decimal>("EndingLatitude")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("end_lat");

                    b.Property<decimal>("EndingLongtitude")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("end_long");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastModifiedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time")
                        .HasColumnName("start_time");

                    b.Property<decimal>("StartingLatitude")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("starting_lat");

                    b.Property<decimal>("StartingLongtitude")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("starting_long");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<decimal>("TotalDistance")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("distance");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.ToTable("DrivingSession", (string)null);
                });

            modelBuilder.Entity("BookingService.Domain.Entities.Feedback", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("booking_id");

                    b.Property<string>("CarFeedback")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("description_car");

                    b.Property<int>("CarRating")
                        .HasColumnType("int")
                        .HasColumnName("rating_car");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("InstructorFeedback")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("description_instructor");

                    b.Property<int>("InstructorRating")
                        .HasColumnType("int")
                        .HasColumnName("rating_instructor");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime>("LastModifiedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.ToTable("Feedback", (string)null);
                });

            modelBuilder.Entity("BookingService.Domain.Entities.Package", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime>("LastModifiedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("upadated_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("name");

                    b.Property<decimal>("RecommendedValue")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.ToTable("Package", (string)null);
                });

            modelBuilder.Entity("BookingService.Domain.Entities.RoadType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<string>("LastModifiedAt")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("updated_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("RoadType", (string)null);
                });

            modelBuilder.Entity("BookingService.Domain.Entities.SessionLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Heading")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("heading");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime>("LastModifiedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<decimal>("Latitude")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("latitude");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("longtitude");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("session_id");

                    b.Property<decimal>("Speed")
                        .HasMaxLength(500)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("speed");

                    b.Property<string>("StreetName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("street_name");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.ToTable("RouteLog", (string)null);
                });

            modelBuilder.Entity("BookingService.Domain.Entities.SessionRoadType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime>("LastModifiedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("RoadTypeId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("road_type_id");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("session_id");

                    b.HasKey("Id");

                    b.HasIndex("RoadTypeId");

                    b.HasIndex("SessionId");

                    b.ToTable("SessionRoadType", (string)null);
                });

            modelBuilder.Entity("BookingService.Domain.Entities.SessionRoute", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime>("LastModifiedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<decimal>("LatitudeStart")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("latitude_start");

                    b.Property<decimal>("LongitudeStart")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("longtitude_start");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("session_id");

                    b.Property<string>("StreetName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("street_name");

                    b.Property<string>("TextInstruction")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("text_instruction");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.ToTable("SessionRoute", (string)null);
                });

            modelBuilder.Entity("BookingService.Domain.Entities.TimeRange", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("booking_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("end_time");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime>("LastModifiedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("update_at");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("start_time");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.ToTable("BookingTimeRange", (string)null);
                });

            modelBuilder.Entity("BookingService.Domain.Entities.Booking", b =>
                {
                    b.HasOne("BookingService.Domain.Entities.CarPackage", "CarPackages")
                        .WithMany("Bookings")
                        .HasForeignKey("CarPackageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CarPackages");
                });

            modelBuilder.Entity("BookingService.Domain.Entities.CarPackage", b =>
                {
                    b.HasOne("BookingService.Domain.Entities.Package", "Packages")
                        .WithMany("CarPackages")
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Packages");
                });

            modelBuilder.Entity("BookingService.Domain.Entities.DrivingSession", b =>
                {
                    b.HasOne("BookingService.Domain.Entities.Booking", "Bookings")
                        .WithMany("DrivingSessions")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("BookingService.Domain.Entities.Feedback", b =>
                {
                    b.HasOne("BookingService.Domain.Entities.Booking", "Bookings")
                        .WithMany("Feedbacks")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("BookingService.Domain.Entities.SessionLog", b =>
                {
                    b.HasOne("BookingService.Domain.Entities.DrivingSession", "DrivingSessions")
                        .WithMany("SessionLogs")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DrivingSessions");
                });

            modelBuilder.Entity("BookingService.Domain.Entities.SessionRoadType", b =>
                {
                    b.HasOne("BookingService.Domain.Entities.RoadType", "RoadTypes")
                        .WithMany("SessionRoadTypes")
                        .HasForeignKey("RoadTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookingService.Domain.Entities.DrivingSession", "DrivingSessions")
                        .WithMany("SessionRoadTypes")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DrivingSessions");

                    b.Navigation("RoadTypes");
                });

            modelBuilder.Entity("BookingService.Domain.Entities.SessionRoute", b =>
                {
                    b.HasOne("BookingService.Domain.Entities.DrivingSession", "DrivingSessions")
                        .WithMany("SessionRoutes")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DrivingSessions");
                });

            modelBuilder.Entity("BookingService.Domain.Entities.TimeRange", b =>
                {
                    b.HasOne("BookingService.Domain.Entities.Booking", "Bookings")
                        .WithMany("TimeRanges")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("BookingService.Domain.Entities.Booking", b =>
                {
                    b.Navigation("DrivingSessions");

                    b.Navigation("Feedbacks");

                    b.Navigation("TimeRanges");
                });

            modelBuilder.Entity("BookingService.Domain.Entities.CarPackage", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("BookingService.Domain.Entities.DrivingSession", b =>
                {
                    b.Navigation("SessionLogs");

                    b.Navigation("SessionRoadTypes");

                    b.Navigation("SessionRoutes");
                });

            modelBuilder.Entity("BookingService.Domain.Entities.Package", b =>
                {
                    b.Navigation("CarPackages");
                });

            modelBuilder.Entity("BookingService.Domain.Entities.RoadType", b =>
                {
                    b.Navigation("SessionRoadTypes");
                });
#pragma warning restore 612, 618
        }
    }
}
